[tool.poetry]
name = "scripts"
version = "0.1.0"
description = ""
authors = ["Justin Barnowski <jbarno54@gmail.com>"]

[tool.poetry.dependencies]
python = "*"

[tool.poetry.dev-dependencies]
pytest = "^3.5"
facebook-sdk = "^2.0"
